### PR TITLE
add swap_bytes

### PR DESCRIPTION
**Pull request by TheIronBorn**
We could add some `llvm.bswap` implementations.

https://godbolt.org/g/jH2FCR suggests this could be better.

### CODE REVIEW

**Comment by TheIronBorn** [comment]
I can't find a decent way to import the shuffle intrinsics

**Comment by gnzlbg** [comment]
You just need to do like x86 does and use the `llvm` intrinsics directly, they are in the llvm module.

**Comment by TheIronBorn** [comment]
I'm trying `use coresimd::simd_llvm::*;` but getting `Could not find simd_llvm in coresimd`

**Comment by TheIronBorn** [comment]
Using what I can see as the exact same technique used in `codegen/mask_reductions`:
```rust
#![allow(unused)]

use coresimd::simd::*;

pub(crate) trait SwapBytes {
    fn swap_bytes(self) -> Self;
}

#[cfg(not(target_arch = "aarch64"))]
impl SwapBytes for u8x2 {
    fn swap_bytes(self) -> Self {
        use coresimd::simd_llvm::simd_shuffle2;

        let shuffled: u8x2 = unsafe { simd_shuffle2(self, self, [1, 0]) };
        u8x2::from_bits(shuffled)
    }
}
```

Gets 
```
error[E0432]: unresolved import `coresimd::simd_llvm`
  --> crates/coresimd/tests/../../../coresimd/ppsv/codegen/swap_bytes.rs:14:23
   |
14 |         use coresimd::simd_llvm::simd_shuffle2;
   |                       ^^^^^^^^^ Could not find `simd_llvm` in `coresimd`

**Comment by gnzlbg** [comment]
If you update or send a PR it is easier for me to look at it.

**Comment by TheIronBorn** [comment]
I found a solution. The weird crate structure was throwing me. Pull coming soon

**Comment by gnzlbg** [comment]
what was the problem?

**Comment by TheIronBorn** [comment]
Macro scopes combined with importing the crate modules by path.

**Pull request closed without merging**
