### PR TITLE
[avx2] add shuffle, insert/extract i128, permute*

### PR DESCRIPTION
**Pull request by governortarkin**
- _mm256_shufflehi_epi16
- _mm256_shufflelo_epi16
- _mm256_inserti128_si256
- _mm256_extracti128_si256
- _mm256_permute2x128_si256
- _mm256_permute4x64_pd
- _mm256_permutevar8x32_ps

### CODE REVIEW

**Comment by BurntSushi** [comment]
Looks like this needs to be rebased on current master.

**Comment by governortarkin** [comment]
@BurntSushi that should do it pending ci.

**Comment by governortarkin** [comment]
Had some time to finish the permutes, so I figured I'd sneak them while this was still open.

**Comment by gnzlbg** [comment]
Looks like the test are failing, also don't forget to `cargo fmt --all` the code with a recent rustfmt nightly (`cargo install rustfmt-nightly --force && cargo fmt -all`).

**Comment by governortarkin** [comment]
@gnzlbg wasn't using `constify_imm8` in `_mm256_permute2x128_si256`. Fixed that + rustfmt.

**Comment by gnzlbg** [comment]
@governortarkin Thank you a lot!

**Pull request merged**
