### PR TITLE
Add SSE _mm_store* intrinsics and _mm_move_ss

### PR DESCRIPTION
**Pull request by nominolo**
Implements SSE `_mm_store*` intrinsics and `_mm_move_ss`

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Looks like i586 may still be failing?

**Comment by nominolo** [comment]
Yeah.. it's also generating some pretty stupid code, so I'll try to setup a local testing environment to better experiment.

**Comment by nominolo** [comment]
OK, ready to merge now.

**Comment by alexcrichton** [comment]
👍 Thanks!

**Pull request merged**
