### PR TITLE
Automatic verification of MIPS MSA intrinsics

### PR DESCRIPTION
**Pull request by gnzlbg**
This PR adds automatic-verification of the MIPS MSA intrinsic type signatures

cc @rbirdic @wzssyqa

### CODE REVIEW

**Comment by gnzlbg** [comment]
The problem is that the C headers that do not include the `__builtin_` use C macros to wrap those, so we can't extract any type information from them, e.g., see: https://github.com/gcc-mirror/gcc/blob/master/gcc/config/mips/msa.h#L52

**Comment by gnzlbg** [comment]
The clang header does the same: https://clang.llvm.org/doxygen/msa_8h_source.html

**Comment by alexcrichton** [comment]
Ah ok that at least means directly using the `__builtin` macros is probably a good idea! Seems fine by me

**Comment by gnzlbg** [comment]
FYI i tried to enable checking the instructions, but something appears to be broken in the code that parses the `assert_instr` macros. It only finds intrinsics in 3/100 intrinsics. I've tried a bit of code golf there, but so much has changed in `syn` in the last years that I'm not really sure if the approach is correct anymore.

**Comment by alexcrichton** [comment]
Ah no worries, if you want to land this an open an issue I can follow-up later poking around to see if I can enable this

**Comment by gnzlbg** [comment]
I'll wait for @rbirdic to review the proposed changes to the `msa` module and merge afterwards.

**Pull request merged**
