### PR TITLE
[arm] v6/v7/v8 run-time tests

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by gnzlbg** [comment]
@alexcrichton I didn't manage to make the `#[simd_test = "v8"]` macros work, but wanted to comit this before I add one or two NEON intrinsics so that we at least have something to improve on.

**Comment by alexcrichton** [comment]
Looks good! What was the error with the macro?

**Comment by gnzlbg** [comment]
I think it did not recognize `+v7` and `+v8` as features.

**Comment by alexcrichton** [comment]
Alas :(

**Pull request merged**
