### PR TITLE
Add support for Intel SHA extensions.

### PR DESCRIPTION
**Pull request by jasondavies**
See #392.

### CODE REVIEW

**Comment by jasondavies** [comment]
Just for keeping track of progress.  I think I've implemented everything in "step 2" now.  I've also pulled in @alexcrichton's initial implementation (thank you!) so much of step 3 is already done aside from tests, which I think is all that remains.

For the tests, is there a preferred approach?  I was thinking of using some fixed test vectors.  I had a quick look at what GCC does, and they actually bring in an implementation of the intrinsics and test that they come up with the same results (though with fixed test vectors).

**Comment by alexcrichton** [comment]
Looks great to me, thanks! For tests I think having fixes inputs/outputs is fine, we're mostly looking for "obviously wrong" bugs rather than smaller corner cases

**Comment by gnzlbg** [comment]
The run-time support parts LGTM. For the tests, it is not about checking the result for every possible input value, but more about exercising that the intrinsics compile correctly and are able to generate correct results. So checking each intrinsic for two different inputs should be more than enough.

**Comment by jasondavies** [comment]
One quick question: why are these assert instruction tests being ignored?

```sh
# CARGO_INCREMENTAL=0 cargo test sha
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs

     Running target/debug/deps/coresimd-3d30e14a0ab5fad2

running 14 tests
test coresimd::x86::sha::assert__mm_sha1msg1_epu32_sha1msg1 ... ignored
```

**Comment by alexcrichton** [comment]
@jasondavies oh to run the instruction assertions you'll need to pass `--release`

**Comment by alexcrichton** [comment]
Awesome, thanks!

**Pull request merged**
