### PR TITLE
[neon] reciprocal square-root estimate

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by gnzlbg** [comment]
Do not merge. @alexcrichton for some reason `cfg_target_feature` is not detecting that neon is enabled (e.g. in aarch64 the neon tests are not running). If I disable the neon checks in arm/mod.rs the tests in aarch64 run and pass, but the arm-v6 and arm-v7 builds fail with a code-gen error. I thought that neon was orthogonal to aarch64 but from this error it seems that LLVM can only generate neon instructions for aarch64. @japaric do you have any experience with any of this?

**Comment by alexcrichton** [comment]
I think you can test this out locally via:

```
$ rustc +nightly -C target-feature=+neon --print cfg --target aarch64-unknown-linux-gnu
debug_assertions
target_arch="aarch64"
target_endian="little"
target_env="gnu"
target_family="unix"
target_has_atomic="128"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_os="linux"
target_pointer_width="64"
target_thread_local
target_vendor="unknown"
unix
```

(note the lack of neon)

unlike...

```
$ rustc +nightly -C target-feature=+neon --print cfg --target arm-unknown-linux-gnueabi
debug_assertions
target_arch="arm"
target_endian="little"
target_env="gnu"
target_family="unix"
target_feature="neon"
target_feature="vfp2"
target_feature="vfp3"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_os="linux"
target_pointer_width="32"
target_thread_local
target_vendor="unknown"
unix
```

Note the presence of neon!

Which leads me to conclude that this may be [an upstream bug](https://github.com/rust-lang/rust/blob/df095cefe28f9fc781e8da02f655903600343506/src/librustc_trans/llvm_util.rs#L91-L97)!

**Comment by gnzlbg** [comment]
@alexcrichton https://github.com/rust-lang/rust/pull/45310

**Comment by alexcrichton** [comment]
👍

**Comment by alexcrichton** [comment]
Support is on master and looks like tests are green! I'll merge.

**Pull request merged**
