### PR TITLE
Sse2

### PR DESCRIPTION
**Pull request by pythoneer**
_mm_cvtsd_si32
_mm_cvtsd_si64
_mm_cvtsd_ss
_mm_cvtss_sd 
_mm_cvttpd_epi32 
_mm_cvttsd_si32 
_mm_cvttsd_si64

### CODE REVIEW

**Comment by BurntSushi** [comment]
LGTM after assert_instr tests are fixed.

**Comment by BurntSushi** [comment]
Oops, looks like merging another PR caused conflicts. Can you rebase?

**Comment by pythoneer** [comment]
now `cvttsd2si64` is also failing here https://travis-ci.org/rust-lang-nursery/stdsimd/jobs/281653879

**Comment by pythoneer** [comment]
this PR is FUBAR closing

**Pull request closed without merging**
