### PR TITLE
MaybeUninit: update to into_initialized

### PR DESCRIPTION
**Pull request by RalfJung**
This is the stdsimd side of https://github.com/rust-lang/rust/pull/58129.

(Having stdsimd in a separate repo means that what would usually be 1 PR turns into 3...)

### CODE REVIEW

**Comment by gnzlbg** [comment]
@RalfJung wait a sec, how did that PR get merged without updating stdsimd ? `stdsimd` should have failed to build as part of `libcore` because of this -.-

**Comment by gnzlbg** [comment]
FWIW, there is a possible 1 PR approach. First you update `stdsimd` upstream to point to your own fork, then you fix the fork as part of your PR, and then you merge that. 

Then you send a PR here, which we merge, and we take care of updating `stdsimd` back to this repo master for you :)

**Comment by RalfJung** [comment]
I left a libcore-private copy of `fn into_inner` which stdsimd uses (and which caused a bors failure because on non-x86 platforms that function is unused :/ ).

> First you update `stdsimd` upstream to point to your own fork

You mean as in, change the rustc branch it tests again?
That'll be "fun" when two people want to do it at the same time. ;)

**Comment by gnzlbg** [comment]
> You mean as in, change the rustc branch it tests again?
> That'll be "fun" when two people want to do it at the same time. ;)

If you ping me or alex we can prevent two people from doing it at the same time. 

There is an alternative 2 PR method, which has the same problem if two people do it at the same time (depending on the changes).  You could update `stdsimd` in your PR to  `stdsimd/master` with your fix, if you send a PR here before that breaks stdsimd master temporarily.  If your PR is reviewed and ready to merge, we could also do just that. 

The safest method is the 3 PR approach, but if you ping us we can tell you if there are others trying to do the same right now or not :P

**Comment by gnzlbg** [comment]
FYI @RalfJung windows is broken, so as long as travis passes everything should be ok.

**Comment by RalfJung** [comment]
The Android and macOS build failure seem to be just timeouts?

**Comment by gnzlbg** [comment]
I've restarted them.

**Pull request merged**
