### PR TITLE
Modernize Docker images

### PR DESCRIPTION
**Pull request by mati865**
Fixes https://github.com/rust-lang-nursery/stdsimd/issues/669

### CODE REVIEW

**Comment by mati865** [comment]
Ping?

I did not touch Android images (they are using Ubuntu 16.04 LTS) but it failed:
```
 curl --retry 5 -O https://dl.google.com/android/repository/android-ndk-r15b-linux-x86_64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 16  928M   16  157M    0     0   174M      0  0:00:05 --:--:--  0:00:05  174M
curl: (56) GnuTLS recv error (-54): Error in the pull function.
The command '/bin/sh -c sh /android/android-install-ndk.sh $ANDROID_ARCH' returned a non-zero code: 56
The command "ci/run-docker.sh $TARGET" exited with 56.
```

**Comment by gnzlbg** [comment]
Weird, I've restarted it.

**Comment by mati865** [comment]
Travis is green.

**Comment by gnzlbg** [comment]
Thank you!

**Pull request merged**
