### PR TITLE
Implement automatic verification for ARM/AArch64 intrinsics

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit implements automatic verification of implement ARM/AArch64
intrinsics. Or it's at least a start! This downloads a snapshot of ARM's
[online documentation][docs] and implements necessary logic to parse
that and use it to verify all the intrinsics. Almost everything
checked out A-OK but a few minor tweaks were needed to the neon
intrinsics and the crc ones needed some renaming.

[docs]: https://developer.arm.com/technologies/neon/intrinsics

### CODE REVIEW

**Comment by alexcrichton** [comment]
All green! I'm gonna go ahead and merge this and use it to update the NEON intrinsic listing

**Comment by alexcrichton** [comment]
cc @myfreeweb for the crc intrinsic naming changes on AArch64

**Comment by gnzlbg** [comment]
> hm, the ones in neon.rs don't start with __?

now they do AFAICT, or which `neon.rs` do you mean? In the intrinsics guide they also have an `__`:

screen shot 2018-12-20 at 21 58 45

**Comment by myfreeweb** [comment]
Not the CRC ones, the NEON ones, visible in the diff here on github: e.g. `vaddd_s64`

**Comment by alexcrichton** [comment]
For whatever reason ARM seems to specify `__crc32cd` yet also specifies `vaddd_s64` (no leading underscores). I'm not really sure why...

**Comment by gnzlbg** [comment]
But those do not have underscores in the intrinsics guide, right?

**Pull request merged**
