### PR TITLE
[example] nbody

### PR DESCRIPTION
**Pull request by gnzlbg**
Ports @huonw 's nbody example from the old simd library.

### CODE REVIEW

**Comment by alexcrichton** [comment]
A great idea! Perhaps this could use `cfg_feature_enabled!` as well to provide a runtime diagnostic when it would otherwise not work?

**Comment by gnzlbg** [comment]
Yes we should definetely improve this:

- clean up the `cfg(target_feature)` macros
- implement the required ARM intrinsics (I am doing this right now, are you on IRC?)
- use run-time feature detection

**Comment by alexcrichton** [comment]
I am indeed on IRC!

**Comment by gnzlbg** [comment]
@alexcrichton why isn't travis running anymore?

**Comment by gnzlbg** [comment]
does this mean I cannot squash? I can't change the past anymore!

**Comment by alexcrichton** [comment]
👍

**Pull request merged**
