### PR TITLE
Sse

### PR DESCRIPTION
**Pull request by gwenn**
Tests are missing...

### CODE REVIEW

**Comment by gwenn** [comment]
Oops... Some constify are missing.

**Comment by alexcrichton** [comment]
Thanks! Did the tests fail to compile or cause LLVM errors? (just wondering if there's a reason to leave them out)

**Comment by gwenn** [comment]
@alexcrichton Sorry, I just didn't take the time to add tests. I will...

**Comment by alexcrichton** [comment]
Ok no worries!

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
