### PR TITLE
[breaking change]: mask argument type of _mm_shuffle_ps

### PR DESCRIPTION
**Pull request by gnzlbg**
**DO NOT MERGE**

If CI passes, I'll push this as a branch, and send a PR to rust-lang/rust to schedule a crater run. Depending on how much code this change breaks, we can re-evaluate what to do with issue #522 .

### CODE REVIEW

**Comment by gnzlbg** [comment]
@alexcrichton so CI passed, shall I send a PR to rust-lang/rust to schedule a crater run ?

**Comment by alexcrichton** [comment]
@gnzlbg sure!

**Comment by gnzlbg** [comment]
I think we should just merge this and deal with the fallout. cc @rust-lang-nursery/libs @Amanieu

**Comment by alexcrichton** [comment]
I believe the crater fun from 6ish months ago was clean right? I forget now the original reason for closing, but I'm personally still in favor for this

**Comment by Amanieu** [comment]
I think this is fine, we are just correcting an "incorrect" function signature and there are no crater failures.

**Comment by gnzlbg** [comment]
I'll send a PR to update stdsimd upstream, and will do a new crater run before the update. There is another breaking change in the pipeline, so I'll try to merge both. If the crater run fails we can always revert this.

**Pull request merged**
