### PR TITLE
Add FXSAVE/FXRSTOR, update Intel SDE, fix xsave tests

### PR DESCRIPTION
**Pull request by gnzlbg**
@alexcrichton could you test this in your Windows system ?

### CODE REVIEW

**Comment by alexcrichton** [comment]
Unfortunately I get the same error :(

**Comment by gnzlbg** [comment]
@alexcrichton in which test?

**Comment by alexcrichton** [comment]
Oh same ones as before, I believe xsaves64 and xsaves

**Comment by gnzlbg** [comment]
It can't be `xsaves` because I disabled it on `x86_64`, but if you say that it's `xsaves64` then I don't know what's going on, the Intel SDE emulator likes that one, even on my mac :/

**Comment by gnzlbg** [comment]
I've just disabled the tests and filled an issue to track them. Would be nice if you could test again there and see if there is any other test broken.

**Comment by gnzlbg** [comment]
@alexcrichton this should be good to go

**Comment by gnzlbg** [comment]
@alexcrichton I am merging this since I am sending a PR that switches to `cross` for cross-compilation and emulating all targets with `qemu` and that one finds at least some of the issues that you mention with `xsave`.

**Pull request merged**
