### PR TITLE
Fixing the GBA in the build script again

### PR DESCRIPTION
**Pull request by Lokathor**
This isn't ready, just a draft, but this is the easiest way to see what the CI itself is gonna do, so here we go.

### CODE REVIEW

**Comment by Lokathor** [comment]
Marked it as "ready" just because Travis wasn't running on it when it was draft only, but we're still not necessarily ready. If this current commit doesn't work out by pure luck I unfortunately can't get back to this for at least 36 hours.

**Comment by Lokathor** [comment]
@gnzlbg looking at the latest build log, any way to get lazy_static out of the build?

**Comment by gnzlbg** [comment]
Just explicitly build `core_arch` and `std_detect`, all other libraries don't make sense for GBA.

**Comment by Lokathor** [comment]
@gnzlbg Well it can successfully build `core_arch`, which was the blocker that started this whole ordeal. We should be all good now. You can accept the PR if you don't have any other concerns.

**Comment by gnzlbg** [comment]
It should be able to build `std_detect` as well (it should be empty) for that target. I'm merging this as is, but it might be worth it to investigate what's going on there.

**Comment by gnzlbg** [comment]
Thank you!

**Pull request merged**
