### PR TITLE
Update proc macro2

### PR DESCRIPTION
**Pull request by lu-zero**
Update to the latest version of proc_macro2, quote and syn.

### CODE REVIEW

**Comment by lu-zero** [comment]
looks like the new rustfmt has different ideas regarding the style and there is something quite fishy going on windows and x86 but it is unrelated to this set.

**Comment by alexcrichton** [comment]
Unfortunately we're hit by a slew of bugs here:

* First the x86 tests seem to be failing I believe because mergefunc was recently landed. These are presumably duplicates with other functions being generated so they're merged and the disassembly is no longer showing us precisely which instruction is being used.
* Next proc-macro2 is [buggy on nightly](https://github.com/rust-lang/rust/issues/50942), causing the verify-x86 builder to build
* I think rustfmt with nightly needs to be run again?

**Comment by alexcrichton** [comment]
I also don't know what's going on yet with Windows, that's just Linux :(

**Comment by alexcrichton** [comment]
Ok Windows looks back to "normal", I think this PR is now purely blocked on figuring out mergefunc

**Comment by alexcrichton** [comment]
Ok I've pushed a commit that will hopefully thwart mergefunc, let's see how it pans out.

**Comment by alexcrichton** [comment]
Alright, all green now!

**Pull request merged**
