### PR TITLE
fix errors/warnings from the stabilization of cfg_target_feature and target_feature

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by alexcrichton** [comment]
r=me, thanks!

**Comment by gnzlbg** [comment]
@alexcrichton 

i686-unknown-linux-gnu:

```shell
error: failed to prepare thin LTO module: Invalid function metadata: outgoing forward refs (Producer: 'LLVM6.0.0' Reader: 'LLVM 6.0.0')
error: aborting due to previous error
error: Could not compile `coresimd`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

* aarch64-unknown-linux-gnu:

```shell
error[E0658]: the target feature `neon` is currently unstable
   --> /checkout/crates/coresimd/src/../../../coresimd/arm/neon.rs:772:18
    |
772 | #[target_feature(enable = "neon")]
    |                  ^^^^^^^^^^^^^^^
    |
    = help: add #![feature(aarch64_target_feature)] to the crate attributes to enable
```

but that feature is enabled AFAICT.

**Comment by alexcrichton** [comment]
I've asked on https://github.com/rust-lang/rust/pull/49904 about the LTO error at https://github.com/rust-lang/rust/pull/49904#issuecomment-382917932. No idea what's going on there :(

**Comment by gnzlbg** [comment]
> No idea what's going on there :(

Crap :/ I probably can't take a look at this till monday; it seems that windows on appveyor has the same problem.

**Comment by alexcrichton** [comment]
In the meantime something magical seems to have happened and we're all green now!

**Pull request merged**
