### PR TITLE
Add RDTSC and RDTSCP intrinsics

### PR DESCRIPTION
**Pull request by shepmaster**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks!

**Comment by gnzlbg** [comment]
Is there a reason why there aren't in i386 ? That's where clang puts them: 

https://github.com/llvm-mirror/clang/blob/a38ba9770a70056f9fdd6c71f819e5db45a105e4/lib/Headers/ia32intrin.h#L64

There doesn't seem to be an llvm feature to enable these conditionally, so I'd guess they are available on all x86 LLVM targets without exceptions.

**Comment by shepmaster** [comment]
TBQH, I just followed the BSWAP intrinsic, although I thought I looked at the Intel manual to see when it was supported. 

Either way, you can assume I didn't know what I was doing ;-)

**Comment by gnzlbg** [comment]
So `_bswap` also belongs in `i386` :D 

https://github.com/gcc-mirror/gcc/blob/master/gcc/config/i386/ia32intrin.h

I'll move them there.

**Pull request merged**
