### PR TITLE
x86: implemented _mm{,256}_maskload_epi{32,64}

### PR DESCRIPTION
**Pull request by Mrowqa**
Hi,

just wanted to ask if I'm doing this in the right way. I will add the documentation and tests soon. Then I will also implement the mask stores.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks great, thanks! r=me w/ tests and docs :)

**Comment by Mrowqa** [comment]
@alexcrichton tests and docs are ready. I will create new PR for mask stores, so you can merge this if everything is okay :)

**Comment by Mrowqa** [comment]
Hm, I have just noticed that I forgot about mask loads for `f32` and `f64` (there was no TODO comment in `avx2.rs`). I will add them soon.

**Comment by BurntSushi** [comment]
@Mrowqa Do you want to do that in a separate PR? That way we can just merge this now.

**Comment by Mrowqa** [comment]
It is fine to merge this now. I will implement the rest of masked loads in a new PR. I have changed the title to something more accurate.

**Comment by alexcrichton** [comment]
@Mrowqa I think this may need a rebase now?

**Comment by Mrowqa** [comment]
As I wrote in #155, it is based on this PR (#152) - that is why I asked you to merge this one before the second one. You have already merged commits from this PR, so it can be safely closed without merging.

**Comment by alexcrichton** [comment]
Ah sorry about that!

**Comment by Mrowqa** [comment]
No worries. I wanted to contribute and you merged the changes anyway :)

**Pull request closed without merging**
